[build]
  base = "frontend"
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  YARN_FLAGS = "--production=false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
